import datetime

x = datetime.datetime.now(datetime.timezone.utc)
print(x.strftime("%a %A %w %d %b %B %m %y %Y %H %I %p %M %S %f %z %Z %j %U %W %c %C %x %X %% %G %u %V"))

# My output
# Tue (short version of weekday) 
# Tuesday (full version of weekday) 
# 2 (weekday as a number from 0 to 6 starting from Sunday) 
# 03 (day of month) 
# Feb (short version of month) 
# February (full version of month) 
# 02 (month as a number from 1 to 12) 
# 26 (short version of year) 
# 2026 (full version of year) 
# 17 (hour UTC+0, 0 - 23) 
# 05 (hour UTC+0, 0 - 12) 
# PM (am/pm) 
# 00 (minute) 
# 42 (second) 
# 980307 (microsecond) 
# +0000 (UTC offset) 
# UTC (timezone) 
# 034 (day number of year) 
# 05 (week number of year from Sunday) 
# 05 (week number of year from Monday) 
# Tue Feb 3 17:00:42 2026 (local version of date and time) 
# 20 (century) 
# 02/03/26 (local version of date) 
# 17:00:42 (local version of time) 
# % (just percentage sign) 
# 2026 (ISO 8601 year) 
# 2 (ISO 8601 weekday) 
# 06 (ISO 8601 week number of year)